version: '3.8'

services:

  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge
        